### ISSUE TITLE
Update create-react-app

### ISSUE THREAD

**Issue by jamesdoc** [theglobechurch/one21#11]
We're current running v1… while v4 is the latest. Time to update!

**Comment by jamesdoc** [comment]
@kbberker Have been looking into this today. The challenge as you have already pointed out is that they strongly discourage mis-matching eslint versions.

Your branch is pulling in `7.20.0` [reference](https://github.com/theglobechurch/one21/blob/bd30a1937a8414cc25047e36dbd1e735d03b5f3f/package.json#L28) while Create React App is shipping with `7.11.0` [reference](https://github.com/facebook/create-react-app/blob/f92c37a6e6636ed1650ffd976c6881f59b1be803/package.json#L27).

Do you foresee major issues with dropping One21 back to `7.11.0`? I've got that running in a branch happily (with all the eslint errors that we need to fix!)

**Comment by kbberker** [comment]
@jamesdoc no I don't think so! I think we should just go with that. It'll be good to update react-scripts. I see you've removed the sass dependency on the same branch `react-scripts`. Shall we get that branch merged into `kbb`? I'll then rebase the `linting` branch back on to that.
